### ISSUE TITLE
Replacing Google Analytics ID with yours

### ISSUE THREAD

**Issue by yoshiharuyamashita** [reber-9/reber-9.com#1]
Hi @reber-9 

I keep getting Google analytics data from your website. Please could you replace my Google Analytics ID with yours in config toml?

Many thanks!

Yoshi

**Comment by reber-9** [comment]
First of all, I'm very sorry, this is my negligence.
And thank you for your template.
I wish you good luck.

**Comment by reber-9** [comment]
Hi @yoshiharuyamashita 

First of all, I'm very sorry, this is my negligence.
And thank you for your template.
I wish you good luck.

Reber-9
